### ISSUE TITLE
Incorrectly using test task

### ISSUE THREAD

**Issue by steve-kaufman** [jbec1901/personal-website#1]
The npm test task should be reserved for unit testing. I recommend you rename this task to 'dev', or rename it to 'start' and rename your current start tast to 'serve'.

**Comment by jbec1901** [comment]
1. test is a reserved word. pretest runs before test and I need the mongodb server to start before anything else starts.
2. because this projects is not a library package there isn't much by way of unit testing that I need to do.
3. because test is a reserved word I can use `npm test` instead of 'npm run dev' and it makes my life 3 characters easier.
4. start cant be renamed to serve because heroku uses the start keyword start the server.
